### ISSUE TITLE
aws-ddb-sink-binding doesn't send data to DynamoDB

### ISSUE THREAD

**Issue by anuj-upadhyay-inferenz** [apache/camel-kamelets#1038]
aws-ddb-sink-binding.yaml
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: aws-ddb-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-ddb-sink
    properties:
      table: kafkaTable
      region: ap-south-1
      accessKey: ********************************
      secretKey: *********************************

```
What i have already checked:
1] Strimzi is setup and working.
2] Kafka producer sends data in proper JSON Format
3] My partition key in the table is also present in the JSON sent by the Kafka producer
4] I also have an elasticsearch-index-sink setup with the same Kafka settings as the source and that sink connector is working perfectly.
5] The accessKey and secretKey properties are set to the AWS_ACCESS_KEY_ID and AWS_SECRET_KEY values respectively.
