### ISSUE TITLE
Provide a way to pass Kamelets arbitrary parameters so that users don't need to extend predefined Kamelets so often

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-kamelets#1244]
A Kamelet has a predefined set of properties that are opinionatedly chosen for ease of use, but oftentimes we later find that there are some more properties needed for the common usages of a Kamelet. In such case, right now the only ways users can do are either 1) extending the Kamelet by themselves from the predefined one, or 2) requesting to add the parameters and waiting for the next release. If Kamelets can provide a generic way to pass arbitrary parameters to the internal Camel endpoints as an advanced configuration option, then it can give users a faster workaround while waiting for the Kamelet to officially support the parameters.

**Comment by tadayosi** [comment]
@oscerd What do you think about this feature request?

One difficulty with implementing such a feature is that there are multiple endpoints in a single Kamelet, so we need to devise a good notation to specify which internal endpoints to apply the passed parameters.

So for example in a KameletBinding with `kafka-source` (notice `extensions`):

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kafka-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-source
    properties:
      bootstrapServers: "The Bootstrap Servers"
      password: "The Password"
      topic: "The Topic Names"
      user: "The Username"
    extensions:
      from:
        endpointOptions: "groupId=my-consumergroup&consumsersCount=4"
      step.1:
        endpointOptions: "..."
      step.2:
        endpointOptions: "..."
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
```
