### ISSUE TITLE
jms-apache-activemq-sink-binding: error during trait customization: component not found for uri

### ISSUE THREAD

**Issue by bjethwan** [apache/camel-kamelets#1304]
IntegrationError
```
camel-k-integration-controller
Cannot reconcile Integration jms-apache-activemq-sink-binding: error during trait customization: component not found for uri "{{activemq-sink-local}}:{{destinationType}}:{{destinationName}}?conn
ectionFactory=%23bean%3A%7B%7BsinkConnectionFactoryBean-local%7D%7D" in camel catalog runtime version 1.16.0
```

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: jms-apache-activemq-sink-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: azure-servicebus-source
    properties:
      connectionString: Endpoint=sb://REMOVED.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=REMOVED
      topicOrQueueName: REMOVED
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: jms-apache-activemq-sink
    properties:
      brokerURL: tcp://active-mq.activemq.svc.cluster.local:61616
      destinationName: REMOVED
```
