### ISSUE TITLE
Content-Type is not set on Kamelets for Cloudevents

### ISSUE THREAD

**Issue by matzew** [apache/camel-kamelets#1828]
Having a `Kamelet` / `Pipe`, such as:

```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: aws-s3-source-pipe
  annotations:
    trait.camel.apache.org/camel.runtime-version: 3.6.0
spec:
  integration:
    dependencies:
    - "camel:cloudevents"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: aws-s3-source
    properties:
      ... some secrets
    dataTypes:
      out:
        scheme: aws2-s3
        format: application-cloudevents
  sink:
    dataTypes:
      in:
        scheme: http
        format: application-cloudevents
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: kamelet
```

I get the following exception from Quarkus Funqy, when trying to process the emitted Cloudevents:

```java
2024-01-11 16:09:51,563 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to / failed, error id: af846418-99ec-4a1a-a4af-ec9192906b2f-1: io.quarkus.funqy.runtime.ApplicationException: java.lang.RuntimeException: Don't know how to get event data (dataContentType: 'null', javaType: 'functions.Input').
test-four-00001-deployment-6b5d6c7f69-flk8p user-container 	at io.quarkus.funqy.runtime.FunctionInvoker.invoke(FunctionInvoker.java:136)
test-four-00001-deployment-6b5d6c7f69-flk8p user-container 	at io.quarkus.funqy.runtime.bindings.knative.events.VertxRequestHandler.dispatch(VertxRequestHandler.java:571)
```

I see similar then I have a different (e.g. `go`) receiver that prints the request:
```
test-three-00001-deployment-54dc897c99-2qgzk user-container Received request
test-three-00001-deployment-54dc897c99-2qgzk user-container POST / HTTP/1.1 test-three.default.svc.cluster.local
test-three-00001-deployment-54dc897c99-2qgzk user-container   Ce-Id: 8B49F74E586030C-0000000000000009
test-three-00001-deployment-54dc897c99-2qgzk user-container   Ce-Specversion: 1.0
test-three-00001-deployment-54dc897c99-2qgzk user-container   X-Forwarded-For: 10.244.0.23, 10.244.0.18
test-three-00001-deployment-54dc897c99-2qgzk user-container   User-Agent: Go-http-client/1.1
test-three-00001-deployment-54dc897c99-2qgzk user-container   Ce-Subject: IMG_3339.jpg
test-three-00001-deployment-54dc897c99-2qgzk user-container   Ce-Time: 2024-01-11T15:08:42.013Z
test-three-00001-deployment-54dc897c99-2qgzk user-container   Forwarded: for=10.244.0.23;proto=http
test-three-00001-deployment-54dc897c99-2qgzk user-container   Prefer: reply
test-three-00001-deployment-54dc897c99-2qgzk user-container   Accept-Encoding: gzip
test-three-00001-deployment-54dc897c99-2qgzk user-container   Ce-Type: org.apache.camel.event.....
test-three-00001-deployment-54dc897c99-2qgzk user-container   X-Request-Id: 2946fb28-f697-4406-9e71-80fb30e3b99a
test-three-00001-deployment-54dc897c99-2qgzk user-container   Content-Length: 883527
test-three-00001-deployment-54dc897c99-2qgzk user-container   Ce-Knativearrivaltime: 2024-01-11T15:08:42.188499068Z
test-three-00001-deployment-54dc897c99-2qgzk user-container   Ce-Source: .bucket.foobar
test-three-00001-deployment-54dc897c99-2qgzk user-container   K-Proxy-Request: activator
test-three-00001-deployment-54dc897c99-2qgzk user-container   Kn-Namespace: default
test-three-00001-deployment-54dc897c99-2qgzk user-container   Traceparent: 00-7ce27116bb576a804f841c7892e8f245-d3e77ecd9906bffa-00
test-three-00001-deployment-54dc897c99-2qgzk user-container   X-Forwarded-Proto: http
```
