### ISSUE TITLE
Support DataRef cloudevent extension

### ISSUE THREAD

**Issue by matzew** [apache/camel-kamelets#1872]
In the CloudEvent spec, there is the `dataref` extension defined:
https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/dataref.md

It would be nice to have a way to make use of this, especially to avoid sending large data, e.g. in sources that shuffle data, like from AWS for example:

```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: aws-s3-source-pipe
  annotations:
    trait.camel.apache.org/camel.runtime-version: 3.6.0
spec:
  integration:
    dependencies:
    - "camel:cloudevents"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: aws-s3-source
    properties:
      .....
```
