### ISSUE TITLE
OpenAI completion kamelet gives me 404 

### ISSUE THREAD

**Issue by matzew** [apache/camel-kamelets#2074]
Inovking the `davinci` engine, via Kamelet gives me a 404:

```
beer-source-pipe-58584b68bb-cdsb5 integration Stacktrace
beer-source-pipe-58584b68bb-cdsb5 integration ---------------------------------------------------------------------------------------------------------------------------------------: org.apache.camel.http.base.HttpOperationFailedException: HTTP operation failed invoking https://api.openai.com/v1/engines/davinci/completions with statusCode: 404
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.component.http.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:452)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.component.http.HttpProducer.lambda$process$1(HttpProducer.java:275)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.component.http.HttpProducer.executeMethod(HttpProducer.java:476)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:246)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:65)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:210)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.processor.errorhandler.NoErrorHandler.process(NoErrorHandler.java:46)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.CamelInternalProcessor.processNonTransacted(CamelInternalProcessor.java:354)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:330)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.processor.Pipeline$PipelineTask.run(Pipeline.java:102)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.doRun(DefaultReactiveExecutor.java:199)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.executeReactiveWork(DefaultReactiveExecutor.java:189)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.tryExecuteReactiveWork(DefaultReactiveExecutor.java:166)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:163)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.CamelInternalProcessor.processNonTransacted(CamelInternalProcessor.java:354)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:330)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:293)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.component.timer.TimerConsumer$1.doRun(TimerConsumer.java:164)
beer-source-pipe-58584b68bb-cdsb5 integration 	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:136)
beer-source-pipe-58584b68bb-cdsb5 integration 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
beer-source-pipe-58584b68bb-cdsb5 integration 	at java.base/java.util.TimerThread.run(Timer.java:516)
beer-source-pipe-58584b68bb-cdsb5 integration 
```

The Kamelet goes like:

```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: beer-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: timer-source
    properties:
      message: What if tomorrow...

  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: openai-completion-action
      properties:
        authorizationToken: <my openai secret key>
  sink:
    properties:
      cloudEventsType: com.corp.my.beer.source
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: kamelet
```

The `authorizationToken` is also a bit confusing.. as OpenAI calls them API_Key, or now Secret_key
