### ISSUE TITLE
mqtt5-source: Issue with wildcard topic. Character encoding issue? The same topic works with the paho-mqtt5 component

### ISSUE THREAD

**Issue by mikoskinen** [apache/camel-kamelets#2248]
The mqtt5-source seems to have issues if the wildcard is in the middle of the topic. For example this doesn't work:

```
- route:
    id: route-05dc
    nodePrefixId: route-4ca
    from:
      id: from-c730
      uri: kamelet:mqtt5-source
      parameters:
        topic: test/+/incoming
        brokerUrl: tcp://localhost:1883
      steps:
        - log:
            id: log-ff85
            message: ${body}
```

The route just doesn't receive any messages:

![image](https://github.com/user-attachments/assets/f839dcb9-ff8e-42c6-8c32-b13fc9e5df5e)

If the kamelet is replaced with paho-mqtt5, things work:

```
- route:
    id: route-05dc
    nodePrefixId: route-4ca
    from:
      id: from-5a40
      uri: paho-mqtt5
      parameters:
        topic: test/+/incoming
      steps:
        - log:
            id: log-ff85
            message: ${body}
```

![image](https://github.com/user-attachments/assets/37288c78-388d-4e25-8945-89b1d832972b)
