### ISSUE TITLE
JSON Schema `int` type seems not right

### ISSUE THREAD

**Issue by lordrip** [apache/camel-kamelets#2453]
There are some kamelets, like the [`rabbitmq-sink.yaml`](https://github.com/apache/camel-kamelets/blob/bcd92cf184e596d0e46bcad4362a18054afcb3bf/kamelets/spring-rabbitmq-sink.kamelet.yaml#L46-L50), that have a `type: int`

```yaml
      port:
        title: Server Port
        description: RabbitMQ broker port
        type: int
        example: 5672
```

According to https://json-schema.org/understanding-json-schema/reference/numeric, it should be either `integer` or `number`

This issue spawned from https://github.com/KaotoIO/kaoto/issues/1899, where we want to support it, but it would be better to fix it upstream first.
