### ISSUE TITLE
catalog: io.fabric8.kubernetes.api.model.apiextensions.v1.JSONSchemaProps does not retain extensions

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-kamelets#284]
i.e. there's no way to get the value of `x-descriptors`

```yaml
  accessKey:
    title: Access Key
    description: The access key obtained from AWS
    type: string
    format: password
    x-descriptors:
    - urn:alm:descriptor:com.tectonic.ui:password
```
