### ISSUE TITLE
To-D doesn't work in a Kamelet

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#449]
With 1.5.0 the parameter substitution won't work in a to-d, like for example azure-storage-blob source and dropbox source.
We have some workaround, like setting an exchange property and then work through headers, but I think we need to address the situation.

**Comment by lburgazzoli** [comment]
```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: azure-storage-blob-source
spec:
  definition:
    title: "Azure Storage Blob Source"
    description: |-
      Consume Files from Azure Storage Blob.
    required:
      - period
      - accountName
      - containerName
      - accessKey
    type: object
    properties:
      period:
        title: Period between Polls
        description: The interval between fetches to the Azure Storage Container in milliseconds
        type: integer
        default: 10000
      accountName:
        title: Account Name
        description: The Azure Storage Blob account name.
        type: string
      containerName:
        title: Container Name
        description: The Azure Storage Blob container name.
        type: string
      accessKey:
        title: Access Key
        description: The Azure Storage Blob access Key.
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
  dependencies:
    - "camel:azure-storage-blob"
    - "camel:kamelet"
    - "camel:core"
    - "camel:jsonpath"
    - "camel:timer"
  flow:
    from:
      uri: "timer:azure-storage-blob-stream"
      parameters:
        period: "{{period}}"
      steps:
      - to:
          uri: "azure-storage-blob:{{accountName}}/{{containerName}}"
          parameters:
            operation: "listBlobs"
            accessKey: "{{accessKey}}"
      - split:
          jsonpath: "$.*"
          steps:
          - set-property:
              name: azureBlobName
              simple: ${body.name}
          - to-d: "azure-storage-blob:{{accountName}}/{{containerName}}?accessKey=RAW({{accessKey}})&operation=getBlob&blobName=${exchangeProperty.azureBlobName}"
          - to: "kamelet:sink"
```

@davsclaus I think the `to-d` here fails because when the real url is computed, the local properties are not more known.
