### ISSUE TITLE
insert-field-action has no documentation on how to set headers/fields as value

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-kamelets#463]
When using the insert-field-action I want to use a header value like the timestamp as the value for the newly inserted field.

Example:

```js
{"message":"hola mundo"}
```
I would expect to have something like this:

```yaml
    - properties:
        field: ts
        value: ${timestamp}
      ref:
        apiVersion: camel.apache.org/v1alpha1
        kind: Kamelet
        name: insert-field-action
```

producing the following message:

```js
{"message":"hola mundo","ts":1628678472}
```
