### ISSUE TITLE
Add x-description URNs to fields to group related properties

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-kamelets#548]
In order to help visual tools to render kamelets, it would be nice if we include metadata information to the properties a kamelet expose, as example we could use some dedicated urn to group authentication related properties:

```yaml
spec:
  definition:
    title: AWS SNS Sink
    type: object
    properties:
      accessKey:
        title: Access Key
        description: The access key obtained from AWS
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
        - urn:camel:group:credentials
      secretKey:
        title: Secret Key
        description: The secret key obtained from AWS
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
        - urn:camel:group:credentials
```

@nicolaferraro @oscerd what do you think ?
