### ISSUE TITLE
Use secrets with KameletBindings

### ISSUE THREAD

**Issue by k0pper** [apache/camel-kamelets#549]
According the the [Kamelets User Documentation](https://camel.apache.org/camel-k/latest/kamelets/kamelets-user.html), a way (3rd one) to configure your Kamelets is to 

1. define a property file
2. create a secret using this property file 
`kubectl create secret generic my-company-log-sink.mynamedconfig --from-file=mynamedconfig.properties`
3. bind the kamelet to the secret 
`kubectl label secret my-company-log-sink.mynamedconfig camel.apache.org/kamelet=my-company-log-sink camel.apache.org/kamelet.configuration=mynamedconfig`
4. write an integration file that uses the Kamelet with the config
```
from('timer:tick')
  .setBody().constant('Hello')
  .to('kamelet:my-company-log-sink/mynamedconfig')
```

Right now, I have to hard-code needed (confidential) properties into the KameletBinding:

_my-binding.kamelet.yaml_
```
...
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: my-telegram-sink
    properties:
      authorizationToken: "abcdefg"
      chatId: "123456"
...
```

Is there also a way of referencing the config in a KameletBinding? I don't want to use java routes only to be able to use secret-based configuration. Something like this:
_my-binding.kamelet.yaml_
```
...
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: my-telegram-sink
      config: mynamedconfig
...
```
