### ISSUE TITLE
Elasticsearch index sink indexId random generator for null

### ISSUE THREAD

**Issue by cwtrex** [apache/camel-kamelets#615]
For events that do not include the header indexId, the existing v0.5.0 of elasticsearch index sink causes document_id "camel-k-index-es" to be generated, but then constantly overwritten by future events that also do not have that header.

I found a past version of the sink had something similar (although not the same) in the following:
```
when:
- simple: "${header[indexId]} == null || ${header[indexId]} == 'NONE'"
   steps:
   - set-header:
       name: "indexId"
       simple: "${header[kafka.TIMESTAMP]}${header[kafka.PARTITION]}${header[kafka.OFFSET]}"
```
The above should either be officially documented as a solution for the above situation or included in the existing sink.
It makes more sense to me that events without the header generate their own rather than generate a single event and then continue to overwrite the same event again and again.
