### ISSUE TITLE
`elasticsearch-index-sink` kamelet should allow empty `indexId`

### ISSUE THREAD

**Issue by valdar** [apache/camel-kamelets#643]
elasticsearch-index-sink kamelet should allow empty indexId i.e. by removing:
```yaml
[...]
          otherwise:
            steps:
            - set-header:
                name: "indexId"
                expression:
                  simple: ${bean:org.apache.camel.support.ShortUuidGenerator?method=generateUuid}
[...]
```
according to https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html it should be auto generated vrom elasticsearch server.
