### ISSUE TITLE
make elasticsearch-index-sink user and password properties optional with "?" syntax

### ISSUE THREAD

**Issue by valdar** [apache/camel-kamelets#704]
after https://issues.apache.org/jira/browse/CAMEL-17479 is released we can change : 
```yaml
    beans:
      - name: local-es
        type: "#class:org.apache.camel.component.elasticsearch.ElasticsearchComponent"
        properties:
            user: "{{user:dummy}}"
            password: "{{password:dummy}}"
```
into:
```yaml
    beans:
      - name: local-es
        type: "#class:org.apache.camel.component.elasticsearch.ElasticsearchComponent"
        properties:
            user: "{{?user}}"
            password: "{{?password}}"
```
