### ISSUE TITLE
Bean reference and processors seem to be non-existent

### ISSUE THREAD

**Issue by dbaggett** [apache/camel-kamelets#736]
It appears that references to beans and processor EIP are not a thing in kamelets. I think the reasons are pretty obvious given it's difficult to do custom logic in a static yaml template. I just want to make sure I am not missing something. Is there an idiomatic way to do custom processing in a kamelet. For example, multicast to multiple http endpoint and aggregating JSON from each respective response is a pattern I've used frequently. How could I replicate this in a kamelet?

**Comment by oscerd** [comment]
Hello and thanks for the interest in camel-kamelets and Apache Camel in general.

In pure Kamelet is really hard to add custom logic like bean, but you can always write your own kamelet without troubles. For example you could something like this:
https://github.com/apache/camel-kamelets/blob/main/kamelets/extract-field-action.kamelet.yaml#L106

This is a way of calling a bean inside the Kamelet body, but I do think you're thinking about calling something like 

from kamelet-source
steps
   kamelet-bean
to kamelet-sink

and this is not possible currently and I think in the future too.

The aim of Kamelets is abstracting the Apache Camel technical details by hiding them into logical unit, like a pre-baked endpoint, like a Kamelet is.

You could always create a yaml route using the camel-kamelet components, like for example:

```
- route:
    from:
      uri: "kamelet:aws-s3-source"
      parameters:
        accesKey: "peppe"
        secretKey: "peppe"
        region: "eu-west-1"
        bucketNameOrArn: "camel-kafka-connector"
        useDefaultCredentialsProvider: "true"
      steps:
        - bean: "org.apache.camel.kamelets.utils.transform.ExtractField"
        - to:
            uri: "kamelet:log-sink"
            parameters:
              showHeaders: "true"
```

In yaml you'll have all the related definition from plain Camel

https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json#L1650

https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json#L446

In case you need to do something complex, my suggestion is using camel-kamelet component as the example above, mixed with the Yaml construct available.

HTH a bit.
